{"name": "test_div_exception[get_div_exception_data0]", "status": "passed", "parameters": [{"name": "get_div_exception_data", "value": "[1, 'a', 'TypeError', \"unsupported operand type(s) for /: 'int' and 'str'\"]"}], "start": 1618301941490, "stop": 1618301941491, "uuid": "3cc0ce90-155b-4dc8-ba26-5abe3796ba78", "historyId": "a6bc11494b2a8f7cee451b821e022696", "testCaseId": "e2ca8cb1f8d27b002a03b922fca102ee", "fullName": "homework_test.test_2th_work.TestCalculator#test_div_exception", "labels": [{"name": "feature", "value": "计算器模块"}, {"name": "story", "value": "计算器除法异常场景用例"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_function')"}, {"name": "tag", "value": "run(order=5)"}, {"name": "parentSuite", "value": "homework_test"}, {"name": "suite", "value": "test_2th_work"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "ShimmerShiningHoon"}, {"name": "thread", "value": "11432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "homework_test.test_2th_work"}]}